backend:
  name: git-gateway
  branch: master

media_folder: "public"
public_folder: "/"

collections:
  - name: "test"
    label: "Tests"
    folder: "content/tests"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{minute}}-{{component}}"
    delete: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tests"}
      - label: "List"
        name: "type"
        widget: "list"
        fields:
          - label: "Field 1"
            name: "field"
            widget: "string"
            default: "Field 1"
          - label: "Field 2"
            name: "field"
            widget: "string"
            default: "Field 2"
      - label: "Component"
        name: "component"
        widget: "select"
        options: ["feature", "blog"]
      - {label: "Image", name: "image", widget: "image", required: false }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

