backend:
  name: git-gateway
  branch: master

media_folder: "public"
public_folder: "/"

collections:
  - name: "test"
    label: "Tests"
    folder: "content/tests"
    create: true
    slug: "{{order}}-{{component}}-{{year}}"
    delete: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tests"}
      - label: "Order"
        name: "order"
        widget: "number"
        valueType: "int"
        min: 1
        max: 20
      - label: "Component"
        name: "component"
        widget: "select"
        options: ["feature", "blog"]
      - {label: "Image", name: "image", widget: "image", required: false }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

