backend:
  name: git-gateway
  branch: master

media_folder: "public"
public_folder: "/"

collections:
  - name: "test"
    label: "Tests"
    folder: "content/tests"
    create: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tests"}
      - {label: "Component", name: "component", widget: "string"}
      - {label: "Image", name: "image", widget: "image" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

