backend:
  name: github
  repo: barnsey-tran/static-web-site
  branch: dev
  base_url: https://githubauthproviderfornetlify.herokuapp.com

media_folder: "public/assets"
# default to media_folder if not provided
public_folder: "/assets"

collections:
  - name: "home"
    label: "Home"
    folder: "content/home"
    create: true
    # order of the segments can be adjusted by the order variable
    slug: "{{order}}-{{year}}-{{month}}-{{day}}-{{minute}}-{{component}}"
    delete: true
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "home"

      - label: "Order"
        name: "order"
        widget: "number"
        valueType: "string"
        min: 1
        max: 20

      # type of react component used to render this segment
      - label: "Component"
        name: "component"
        widget: "select"
        options: ["feature", "news"]

      - label: "Image"
        name: "image"
        widget: "image"
        required: false

      - label: "Image Position"
        name: "imagePosition"
        widget: "select"
        options: ["left", "right"]
        default: "left"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Description"
        name: "description"
        widget: "text"

      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false

  # news page
  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    delete: true
    slug: "{{year}}-{{month}}-{{day}}-{{minute}}-{{slug}}"
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "news"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Date"
        name: "name"
        widget: "date"
        default: ""
        format: "Do MMM YYYY"

      - label: "Image"
        name: "image"
        widget: "image"
        required: false

      - label: "Description"
        name: "description"
        widget: "text"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"
